// Code generated by SQLBoiler 4.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	AuthenticationCodes string
	Passports           string
	Users               string
}{
	AuthenticationCodes: "authentication_codes",
	Passports:           "passports",
	Users:               "users",
}
